<?php

// @codingStandardsIgnoreFile

$uniqueid = 'instagram-widget-' . uniqid();
$imagesPerRow = $this->getData('images_per_row');
$openImagesInNewTab = ($this->getData('images_in_new_tab')) ? 'target="_blank"' : '';
$imagesHavePadding = ($this->getData('images_have_padding')) ? 'use-padding' : '';
$imagesHaveCaption = ($this->getData('images_have_caption')) ? true : false;
$useImageShuffle = ($this->getData('optimize_image_layout')) ? true : false;
$useImageLazyLoad = ($this->isLazyLoadEnabled() && $this->getData('enable_lazyload'));
$showVideos = ($this->getData('show_videos')) ? true : false;
$description = trim($this->getData('description') ?? '');
$backgroundColor = trim($this->getData('background_color') ?? '');
$title = trim($this->getData('title') ?? '');
$limit = intval($this->getData('limit') ?? '');
$token = $this->getInstagramToken();
$imagesAltTag = $this->getData('images_alt_text') ?? '0';
$imagesAltLabel = '';
$useHashTagFilter = ($this->getData('use_hashtag_filter')) ? true : false;
$hashTagFilter = trim($this->getData('hashtag_filter') ?? '');


$lazyloadPlaceholderWidth = $this->getLazyLoadPlaceholderWidth() ?? '100%';
switch ($imagesAltTag) {
    case '2':
        $imagesAltLabel = $block->escapeHtml(trim($this->getData('custom_alt_text')));
        break;
    case '0':
    default:
        $imagesAltLabel = '';
        break;
}
?>
<div class="instagram-widget-container " <?php if ($backgroundColor) : ?> style="background-color: <?php /* @noEscape */ echo $backgroundColor; ?>" <?php endif; ?>>
    <?php if ($title || $description) : ?>
    <div class="instagram-heading-title center">
        <?php if ($title) :  ?>
            <h3><?php echo $block->escapeHtml($title) ?></h3>
        <?php endif; ?>
        <?php if ($description) :  ?>
            <span class="center"><?php echo $block->escapeHtml($description) ?></span>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div id="<?php /* @noEscape */ echo $uniqueid; ?>" class="instagram-photos <?php /* @noEscape */ echo $imagesPerRow . ' ' . $imagesHavePadding ?>" ></div>
</div>
<div class="clear" >&nbsp;</div>
<script>
    require([
        'jquery',
        'instagramFeedBasic',
        'shufflejs',
        'underscore'
        <?php if ($useImageLazyLoad) : ?>
     ,'WeltPixel_LazyLoading/js/jquery_lazyload'
<?php endif  ?>
        ],
        function ($, instagramFeedBasic, Shuffle, _) {
            var $instagramPhotosEl = $('#<?php /* @noEscape */ echo $uniqueid; ?>');
            if( $instagramPhotosEl.length > 0 ){

                $instagramPhotosEl.each(function() {
                    var instaGramTarget ='#<?php /* @noEscape */ echo $uniqueid; ?>',
                        instaGramCount = <?php /* @noEscape */ echo $limit ?>,
                        instagramToken = '<?php /* @noEscape */ echo $token ?>',
                        instaImageNewTab = '<?php /* @noEscape */  echo $openImagesInNewTab ?>',
                        instaImagePadding = '<?php /* @noEscape */ echo $imagesHavePadding ?>',
                        useImageShuffle = '<?php /* @noEscape */ echo $useImageShuffle ?>',
                        useImageCaption = '<?php /* @noEscape */ echo $imagesHaveCaption ?>',
                        useImageLazyLoad = '<?php /* @noEscape */ echo $useImageLazyLoad ?>',
                        showVideos = '<?php /* @noEscape */ echo $showVideos ?>',
                        lazyLoadPlaceholderWidth = '<?php /* @noEscape */ echo $lazyloadPlaceholderWidth ?>',
                        useHashTagFilter = '<?php /* @noEscape */ echo $useHashTagFilter ?>',
                        hashTagFilter = '<?php /* @noEscape */ echo $hashTagFilter ?>',
                        instaImageAltTag = <?php /* @noEscape */ echo $imagesAltTag ?>,
                        instaImageAltLabel = '<?php /* @noEscape */ echo $imagesAltLabel ?>';


                    if( !instaGramCount ) { instaGramCount = 6; }
                    $.instagramFeedBasic({
                        'container': instaGramTarget,
                        'items': instaGramCount,
                        'token': instagramToken,
                        'image_new_tab' : instaImageNewTab,
                        'display_captions' : useImageCaption,
                        'image_padding' : instaImagePadding,
                        'image_alt_tag': instaImageAltTag,
                        'image_alt_label': instaImageAltLabel,
                        'image_lazy_load' : useImageLazyLoad,
                        'show_videos': showVideos,
                        'useHashTagFilter': useHashTagFilter,
                        'hashTagFilter': hashTagFilter,
                        'lazy_load_placeholder_width' : lazyLoadPlaceholderWidth,
                        'after': function() {
                            if (useImageShuffle) {
                               new Shuffle($instagramPhotosEl);
                                if (useImageLazyLoad) {
                                    $(window).scroll(_.debounce(function () {
                                        var evt = window.document.createEvent('UIEvents');
                                        evt.initUIEvent('resize', true, false, window, 0);
                                        window.dispatchEvent(evt);
                                    }, 350));
                                }
                            }
                        }
                    });
                });
            }
        });
</script>
